platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 16 x64
  - npm config set registry https://registry.npmmirror.com
  - npm install yarn -g
  - yarn install

build_script:
  - yarn run build

test: off

branches:
  only:
    - main

environment:
  GH_TOKEN:
   secure: e9i9Y64N/YOsD8q+osrxG+4d+gPVP4uKEN6qoB7qPL4qWSB1NcPZs8uKEWwlE1kC
